
outdir='/home/psadil/matlab/toolbox/standalone';
outfile='spm12';
compiler.package.docker(...
    [{fullfile(outdir, outfile)}; {fullfile(outdir, sprintf('%s.ctf', outfile))}], ...
    fullfile(outdir, 'requiredMCRProducts.txt'), ...
    "ImageName","psadil/cat12",...
    "DockerContext", 'docker', ...
    "ExecuteDockerBuild", 'off', ...
    "AdditionalPackages", {'xvfb', 'x11-utils', 'libglx-mesa0',  'libgl1-mesa-dri'},...
    "AdditionalInstructions", ...
    {'ENV MCRROOT=/opt/matlabruntime/R2024b', ...
    'ENV MCR_INHIBIT_CTF_LOCK=1', ...
    'ENV LD_LIBRARY_PATH=${MCRROOT}/runtime/glnxa64:${MCRROOT}/bin/glnxa64:${MCRROOT}/sys/os/glnxa64:${MCRROOT}/sys/opengl/lib/glnxa64', ...
    'RUN /usr/bin/mlrtapp/spm12 --version', ...
    }...
    )
